### PR TITLE
added support for auxiliary matrices for non-conservative interface

### PR DESCRIPTION
**Pull request by asartori86**
this is a quick(not so) and dirty (not so) implementation for the auxiliary matrices. to ease the implementation of aux_matrices I imposed the coupling of the preconditioner to the aux_matrices 

looking at this implementation it emerges that:
- there is much code that is repeated in `assemble_system/preconditioner/aux_matrices` in file `pidomus.cc` suggesting to treat both system and preconditioner as aux_matrix
- it could be designed a `struct` which contains
  - matrix
  - coupling
  - constraints

### CODE REVIEW

**Comment by asartori86** [comment]
I've just implement them for the non-conservative case

**Comment by luca-heltai** [comment]
I'd suggest to remove aux from everywhere. Next PR.

**Comment by asartori86** [comment]
> I'd suggest to remove aux from everywhere

intendi fare il revert di questa PR o cambiare il nome da `aux_matrix` a `matrix`?

**Comment by luca-heltai** [comment]
intendo fare un nuovo PR, ristrutturando un po' tutto. prima vorrei pianificare con voi...

**Pull request merged**
