### PR TITLE
add a flag to avoid to press enter

### PR DESCRIPTION
**Pull request by ESeNonFossiIo**

### CODE REVIEW

**Comment by luca-heltai** [comment]
This is already present by default in Teuchos CLI. Why add another one?

**Comment by ESeNonFossiIo** [comment]
Are you sure?
This bool enables or deny a break after print_debug...

**Comment by ESeNonFossiIo** [comment]
"--echo-command-line" !

**Comment by luca-heltai** [comment]
```
Usage: ./pidomus.g [options]
  options:
  --help                               Prints this help message
  --pause-for-debugging                Pauses for user input to allow attaching a debugger
  --echo-command-line                  Echo the command-line but continue as normal
```

**Comment by luca-heltai** [comment]
The right option should be

```
./pidomus.g --pause-for-debugging    
```

which is already there. For this to work, you have to move MPI etc before...

**Pull request closed without merging**
