### PR TITLE
Navier stokes3 d

### PR DESCRIPTION
**Pull request by ESeNonFossiIo**
I continue to receive this error message:

```
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```
- lldb is useless: the message is the same.
- I have tried printing everything -> nothing

Any Idea?

In attachment the code I use to generate the grid. 

[step-1.cc.zip](https://github.com/mathLab/pi-DoMUS/files/160572/step-1.cc.zip)

### CODE REVIEW

**Comment by asartori86** [comment]
I cannot reproduce it on my laptop

**Comment by ESeNonFossiIo** [comment]
```
[eduroam-31-132:29876] *** Process received signal ***
[eduroam-31-132:29876] Signal: Segmentation fault: 11 (11)
[eduroam-31-132:29876] Signal code: Address not mapped (1)
[eduroam-31-132:29876] Failing at address: 0x7f9feb000050
[eduroam-31-132:29875] *** Process received signal ***
[eduroam-31-132:29875] Signal: Segmentation fault: 11 (11)
[eduroam-31-132:29875] Signal code: Address not mapped (1)
[eduroam-31-132:29875] Failing at address: 0x7f8023000050
[eduroam-31-132:29876] [ 0] [eduroam-31-132:29875] [ 0] 0   libsystem_platform.dylib            0x00007fff9b327eaa _sigtramp + 26
[eduroam-31-132:29876] [ 1] 0   ???                                 0x0000000103956000 0x0 + 4355088384
[eduroam-31-132:29876] [ 2] 0   libsystem_platform.dylib            0x00007fff9b327eaa _sigtramp + 26
[eduroam-31-132:29875] [ 1] 0   ???                                 0x0000000109884000 0x0 + 4454891520
[eduroam-31-132:29875] [ 2] 0   libdeal_II.8.5.0-pre.dylib          0x000000010685cc28 _ZN6dealii16TrilinosWrappers3MPI6Vector6reinitERKNS_8IndexSetERKP19ompi_communicator_tb + 88
[eduroam-31-132:29876] [ 3] 0   libdeal_II.8.5.0-pre.dylib          0x000000010c78dc28 _ZN6dealii16TrilinosWrappers3MPI6Vector6reinitERKNS_8IndexSetERKP19ompi_communicator_tb + 88
[eduroam-31-132:29875] [ 3] 0   libdeal_II.8.5.0-pre.dylib          0x00000001062c2a00 _ZN6dealii16TrilinosWrappers3MPI11BlockVector6reinitERKNSt3__16vectorINS_8IndexSetENS3_9allocatorIS5_EEEERKP19ompi_communicator_tb + 608
[eduroam-31-132:29876] [ 4] 0   libpidomus-lib.dylib                0x00000001039a81ed _ZN7piDoMUSILi2ELi2E10LATrilinosE10setup_dofsERKb + 3405
[eduroam-31-132:29876] [ 5] 0   libpidomus-lib.dylib                0x00000001039a7125 _ZN7piDoMUSILi2ELi2E10LATrilinosE3runEv + 181
[eduroam-31-132:29876] [ 6] 0   libdeal_II.8.5.0-pre.dylib          0x000000010c1f3a00 _ZN6dealii16TrilinosWrappers3MPI11BlockVector6reinitERKNSt3__16vectorINS_8IndexSetENS3_9allocatorIS5_EEEERKP19ompi_communicator_tb + 608
[eduroam-31-132:29875] [ 4] 0   libpidomus-lib.dylib                0x00000001098d31ed _ZN7piDoMUSILi2ELi2E10LATrilinosE10setup_dofsERKb + 3405
[eduroam-31-132:29875] [ 5] 0   libpidomus-lib.dylib                0x00000001098d2125 _ZN7piDoMUSILi2ELi2E10LATrilinosE3runEv + 181
[eduroam-31-132:29875] [ 6] 0   fluid-dynamics                      0x00000001036f1783 main + 1779
[eduroam-31-132:29876] [ 7] 0   libdyld.dylib                       0x00007fff90b865ad start + 1
[eduroam-31-132:29876] [ 8] 0   ???                                 0x0000000000000002 0x0 + 2
0   fluid-dynamics                      0x000000010961f783 main + 1779
[eduroam-31-132:29875] [ 7] 0   libdyld.dylib                       0x00007fff90b865ad start + 1
[eduroam-31-132:29875] [ 8] 0   ???                                 0x0000000000000002 0x0 + 2
[eduroam-31-132:29875] *** End of error message ***
[eduroam-31-132:29876] *** End of error message ***
```

**Comment by ESeNonFossiIo** [comment]
https://groups.google.com/forum/#!topic/dealii/SxVTHGxQ92s

**Comment by ESeNonFossiIo** [comment]
https://github.com/dealii/dealii/pull/2343 Solve the issue! :D

**Pull request merged**
