### PR TITLE
close #148

### LINKED ISSUE #148: Manifold
```
An error occurred in line <114> of file <----------------
An error occurred in line <114> of file <../source/base/subscriptor.cc> in function
    virtual dealii::Subscriptor:../source/base/subscriptor.cc> in function
    virtual dealii::Subscriptor::~:~Subscriptor()
The violated condition waSubscriptor()
The violated condition wass:
    counter =:
    counter == 0
The name = 0
The name and caand call sequence of the exception was:
    ExcInUse (counter, obll sequence of the exception wasject_info->name(), infostring)
Additional Information:
Object :
    ExcInUse (counter, object_info->name(), infostring)
Additional Information:
Object of class N6dealii17Hyof class N6dealii17HyperBallBoperBallBoundaryILi2ELi2EEE is stillundaryILi2ELi2EEE is still used by 1 other objects.

(Additional informati used by 1 other objects.

(Additional ion: <none>)
```

### PR DESCRIPTION
**Pull request by ESeNonFossiIo**

### CODE REVIEW

**Comment by luca-heltai** [comment]
This really fixes things?

**Comment by luca-heltai** [comment]
ParsedGridRefinement stores something about the solution/the manifold??

**Comment by ESeNonFossiIo** [comment]
Sembra di sì

## 

Mauro

**Comment by ESeNonFossiIo** [comment]
A me non risulta 

## 

Mauro

**Pull request merged**
