### PR TITLE
Small fixes for doc

### PR DESCRIPTION
**Pull request by luca-heltai**

### CODE REVIEW

**Comment by ESeNonFossiIo** [comment]
Can I merge?

**Comment by luca-heltai** [comment]
I cannot, so someone else should... ;)

**Comment by ESeNonFossiIo** [comment]
It seems I have not write access:
`Only those with write access to this repository can merge pull requests.`

**Comment by luca-heltai** [comment]
Try again.

**Comment by luca-heltai** [comment]
Now you should be one of the administrators

**Pull request merged**
