### PR TITLE
fixed scalar reaction diffusion

### PR DESCRIPTION
**Pull request by asartori86**

### CODE REVIEW

**Comment by asartori86** [comment]
@luca-heltai @gpitton see if this works for you.

**Comment by gpitton** [comment]
@asartori86 @luca-heltai 

I tried with both your scalar-convection-diffusion branches (on Ulysses, with the mathlab dependencies), but I'm having the following error message at compile time:

```
pidomus.h:40:36: fatal error: deal2lkit/imex_stepper.h: No such file or directory
 #include <deal2lkit/imex_stepper.h>
```

maybe I need to update deal2lkit?

**Comment by luca-heltai** [comment]
Yes. I'll update it right now on ulisses.

**Comment by luca-heltai** [comment]
(64 bits one was already up to date. I forgot to update 32 bits one. sorry.)

**Comment by gpitton** [comment]
Sorry, I was too fast. It compiles fine, but it looks like it's not seeing the correct Dirichlet boundary conditions, and produces identically zero solutions.
However the prm file looks fine to me (the bc are indeed 4x(1-x) on the boundary n.3)

**Pull request merged**
